# PowerShell script to insert German translations

$filePath = "c:\Users\denis\Pantryai\contexts\translations.js"
$content = Get-Content $filePath -Raw

# German translations to add (138 keys)
$germanTranslations = @"
		nutrition: 'Nährwerte',
		calories: 'Kalorien',
		protein: 'Eiweiß',
		carbs: 'Kohlenhydrate',
		fat: 'Fett',
		perServing: 'pro Portion',
		allTime: 'Alle',
		quickRecipes: 'Schnell (< 30 Min.)',
		mediumRecipes: 'Mittel (30-60 Min.)',
		longRecipes: 'Lang (> 60 Min.)',
		allDiets: 'Alle',
		vegetarian: 'Vegetarisch',
		vegan: 'Vegan',
		glutenFree: 'Glutenfrei',
		lowCalorie: 'Kalorienarm',
		rateThisRecipe: 'Dieses Rezept bewerten',
		wouldMakeAgain: 'Würde ich wieder machen',
		saveRating: 'Bewertung speichern',
		ratingSaved: 'Bewertung gespeichert!',
		thankYouFeedback: 'Vielen Dank für Ihr Feedback!',
		failedToSaveRating: 'Bewertung konnte nicht gespeichert werden',
		addToCollection: 'Zur Sammlung hinzufügen',
		favorite: 'Favorit',
		cooked: 'Gekocht',
		wantToTry: 'Möchte ich ausprobieren',
		collectionUpdated: 'Sammlung aktualisiert!',
		addedToFavorites: 'Zu Favoriten hinzugefügt',
		removedFromFavorites: 'Aus Favoriten entfernt',
		markedAsCooked: 'Als gekocht markiert',
		removedFromCooked: 'Aus gekochten Rezepten entfernt',
		addedToWantToTry: 'Zur Liste „Möchte ich ausprobieren" hinzugefügt',
		removedFromWantToTry: 'Aus Liste „Möchte ich ausprobieren" entfernt',
		failedToUpdateCollection: 'Sammlung konnte nicht aktualisiert werden',
		savedRecipes: 'Gespeicherte Rezepte',
		favorites: 'Favoriten',
		noRecipesMatchFilter: 'Keine Rezepte entsprechen den Filtern',
		tryDifferentFilter: 'Versuchen Sie andere Filter',
		clearFilters: 'Filter löschen',
		ingredientsToInclude: 'Zutaten einschließen',
		ingredientsAvailableForRecipe: 'Zutaten für das Rezept verfügbar',
		additionalGuidance: 'Zusätzliche Anweisungen',
		guidancePlaceholder: 'z.B.: keine Nüsse, natriumarm...',
		clearGuidance: 'Anweisungen löschen',
		open: 'Öffnen',
		confirmRemove: 'Entfernen bestätigen',
		confirmRemoveMessage: 'Möchten Sie dieses Rezept wirklich entfernen?',
		removed: 'Entfernt',
		recipeRemoved: 'Rezept entfernt',
		failedToRemove: 'Rezept konnte nicht entfernt werden',
		selectAll: 'Alle auswählen',
		deselectAll: 'Alle abwählen',
		account: 'Konto',
		myAccount: 'Mein Konto',
		login: 'Anmelden',
		loginOrSignup: 'Anmelden / Registrieren',
		createAccount: 'Konto erstellen',
		alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
		signOut: 'Abmelden',
		signOutConfirm: 'Möchten Sie sich wirklich abmelden?',
		signedOutSuccess: 'Erfolgreich abgemeldet',
		loginSuccess: 'Erfolgreich angemeldet',
		loginFailed: 'Anmeldung fehlgeschlagen',
		signupFailed: 'Registrierung fehlgeschlagen',
		upgradeFailed: 'Upgrade fehlgeschlagen',
		accountCreated: 'Konto erfolgreich erstellt!',
		accountUpgraded: 'Konto erfolgreich aktualisiert!',
		youNowHave: 'Sie haben jetzt',
		scans: 'Scans',
		password: 'Passwort',
		confirmPassword: 'Passwort bestätigen',
		displayName: 'Anzeigename',
		fillAllFields: 'Bitte füllen Sie alle Felder aus',
		passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
		passwordTooShort: 'Passwort muss mindestens 6 Zeichen lang sein',
		invalidEmail: 'Ungültige E-Mail-Adresse',
		userDisabled: 'Dieses Konto wurde deaktiviert',
		userNotFound: 'Kein Konto mit dieser E-Mail-Adresse gefunden',
		wrongPassword: 'Falsches Passwort',
		invalidCredentials: 'Ungültige Anmeldedaten',
		tooManyAttempts: 'Zu viele Versuche. Bitte versuchen Sie es später erneut',
		networkError: 'Netzwerkfehler. Überprüfen Sie Ihre Verbindung',
		emailInUse: 'Diese E-Mail-Adresse wird bereits verwendet',
		weakPassword: 'Passwort ist zu schwach',
		guestAccount: 'Gastkonto',
		permanentAccount: 'Dauerhaftes Konto',
		guestAccountWarning: 'Ihre Daten können verloren gehen, wenn Sie die App deinstallieren',
		userId: 'Benutzer-ID',
		upgradeAccount: 'Konto aktualisieren',
		upgradeAccountDesc: 'Erstellen Sie ein dauerhaftes Konto, um Ihre Daten zu sichern',
		upgradeNow: 'Jetzt aktualisieren',
		existingAccount: 'Bestehendes Konto',
		existingAccountDesc: 'Melden Sie sich an, um Ihre Daten zu synchronisieren',
		loginExisting: 'Mit bestehendem Konto anmelden',
		switchedToExistingAccount: 'Zu bestehendem Konto gewechselt',
		welcomeTagline: 'Ihre intelligente Vorratskammer. Null Verschwendung.',
		welcomeTitle: 'Willkommen bei Shelfze',
		welcomeSubtitle: 'Lebensmittel verfolgen. Rezepte generieren. Abfall reduzieren.',
		tryItFirst: 'Zuerst ausprobieren',
		noAccountNeeded: 'Kein Konto zum Starten erforderlich',
		startScanningNow: 'Jetzt mit dem Scannen beginnen',
		guestScansLimit: 'Limit: 50 Scans',
		guestRecipesLimit: 'Limit: 5 Rezepte',
		dataSavedLocally: 'Daten lokal gespeichert',
		continueAsGuest: 'Als Gast fortfahren',
		createFreeAccount: 'Kostenloses Konto erstellen',
		recommended: 'Empfohlen',
		freeScansLimit: '250 Scans/Monat',
		freeRecipesLimit: '50 Rezepte/Monat',
		monthlyBonus: 'Monatlicher Bonus',
		syncAcrossDevices: 'Synchronisierung über Geräte',
		secureBackup: 'Sichere Sicherung',
		getStarted: 'Loslegen',
		upgradeAnytime: 'Sie können jederzeit auf Premium upgraden',
		tier: 'Stufe',
		anonymous: 'Anonym',
		free: 'Kostenlos',
		scansRemaining: 'Verbleibende Scans',
		recipesRemaining: 'Verbleibende Rezepte',
		unlimited: 'Unbegrenzt',
		upgradeToPremium: 'Auf Premium upgraden',
		limitReached: 'Limit erreicht',
		scansLimitReached: 'Scan-Limit erreicht',
		recipesLimitReached: 'Rezept-Limit erreicht',
		createAccountToGetMore: 'Erstellen Sie ein Konto, um mehr Scans und Rezepte zu erhalten',
		upgradeToPremiumMessage: 'Upgraden Sie auf Premium für unbegrenzte Scans und Rezepte',
		monthlyBonusAdded: 'Monatlicher Bonus hinzugefügt!',
		giftCode: 'Geschenkcode',
		redeemGiftCode: 'Geschenkcode einlösen',
		enterGiftCode: 'Geben Sie Ihren Geschenkcode ein',
		redeem: 'Einlösen',
		giftCodeSuccess: 'Geschenkcode erfolgreich eingelöst!',
		giftCodeInvalid: 'Ungültiger Geschenkcode',
		giftCodeUsed: 'Dieser Code wurde bereits verwendet',
		giftCodeExpired: 'Dieser Code ist abgelaufen',
		haveGiftCode: 'Haben Sie einen Geschenkcode?',
"@

# Find the line with German failedToUpdate and insert before the closing })
$pattern = "(\s+failedToUpdate: 'Artikel konnte nicht aktualisiert werden',\r?\n)(\s+\}\),)"
$replacement = "`$1$germanTranslations`r`n`$2"
$content = $content -replace $pattern, $replacement

# Save the file
$content | Set-Content $filePath -NoNewline

Write-Host "✅ German translations added successfully!"
