# PowerShell script to insert Italian translations

$filePath = "c:\Users\denis\Pantryai\contexts\translations.js"
$content = Get-Content $filePath -Raw

# Italian translations to add (141 keys)
$italianTranslations = @"
		nutrition: 'Nutrizione',
		calories: 'Calorie',
		protein: 'Proteine',
		carbs: 'Carboidrati',
		fat: 'Grassi',
		perServing: 'per porzione',
		allTime: 'Tutte',
		quickRecipes: 'Veloci (< 30 min)',
		mediumRecipes: 'Medie (30-60 min)',
		longRecipes: 'Lunghe (> 60 min)',
		allDiets: 'Tutte',
		vegetarian: 'Vegetariana',
		vegan: 'Vegana',
		glutenFree: 'Senza glutine',
		lowCalorie: 'Basso contenuto calorico',
		rateThisRecipe: 'Valuta questa ricetta',
		wouldMakeAgain: 'La rifarei',
		saveRating: 'Salva valutazione',
		ratingSaved: 'Valutazione salvata!',
		thankYouFeedback: 'Grazie per il tuo feedback!',
		failedToSaveRating: 'Impossibile salvare la valutazione',
		addToCollection: 'Aggiungi alla raccolta',
		favorite: 'Preferito',
		cooked: 'Cucinato',
		wantToTry: 'Voglio provare',
		collectionUpdated: 'Raccolta aggiornata!',
		addedToFavorites: 'Aggiunto ai preferiti',
		removedFromFavorites: 'Rimosso dai preferiti',
		markedAsCooked: 'Segnato come cucinato',
		removedFromCooked: 'Rimosso dai cucinati',
		addedToWantToTry: 'Aggiunto alla lista "Voglio provare"',
		removedFromWantToTry: 'Rimosso dalla lista "Voglio provare"',
		failedToUpdateCollection: 'Impossibile aggiornare la raccolta',
		savedRecipes: 'Ricette salvate',
		favorites: 'Preferiti',
		noRecipesMatchFilter: 'Nessuna ricetta corrisponde ai filtri',
		tryDifferentFilter: 'Prova filtri diversi',
		clearFilters: 'Cancella filtri',
		ingredientsToInclude: 'Ingredienti da includere',
		ingredientsAvailableForRecipe: 'ingredienti disponibili per la ricetta',
		additionalGuidance: 'Istruzioni aggiuntive',
		guidancePlaceholder: 'Ad esempio: niente noci, basso contenuto di sodio...',
		clearGuidance: 'Cancella istruzioni',
		open: 'Apri',
		confirmRemove: 'Conferma rimozione',
		confirmRemoveMessage: 'Sei sicuro di voler rimuovere questa ricetta?',
		removed: 'Rimosso',
		recipeRemoved: 'Ricetta rimossa',
		failedToRemove: 'Impossibile rimuovere la ricetta',
		selectAll: 'Seleziona tutto',
		deselectAll: 'Deseleziona tutto',
		account: 'Account',
		myAccount: 'Il mio account',
		login: 'Accedi',
		loginOrSignup: 'Accedi / Registrati',
		createAccount: 'Crea account',
		alreadyHaveAccount: 'Hai già un account?',
		signOut: 'Esci',
		signOutConfirm: 'Sei sicuro di voler uscire?',
		signedOutSuccess: 'Disconnessione riuscita',
		loginSuccess: 'Accesso riuscito',
		loginFailed: 'Accesso fallito',
		signupFailed: 'Registrazione fallita',
		upgradeFailed: 'Aggiornamento fallito',
		accountCreated: 'Account creato con successo!',
		accountUpgraded: 'Account aggiornato con successo!',
		youNowHave: 'Ora hai',
		scans: 'scansioni',
		password: 'Password',
		confirmPassword: 'Conferma password',
		displayName: 'Nome visualizzato',
		fillAllFields: 'Compila tutti i campi',
		passwordsDoNotMatch: 'Le password non corrispondono',
		passwordTooShort: 'La password deve contenere almeno 6 caratteri',
		invalidEmail: 'Indirizzo email non valido',
		userDisabled: 'Questo account è stato disabilitato',
		userNotFound: 'Nessun account trovato con questo indirizzo email',
		wrongPassword: 'Password errata',
		invalidCredentials: 'Credenziali non valide',
		tooManyAttempts: 'Troppi tentativi. Riprova più tardi',
		networkError: 'Errore di rete. Controlla la tua connessione',
		emailInUse: 'Questo indirizzo email è già in uso',
		weakPassword: 'La password è troppo debole',
		guestAccount: 'Account ospite',
		permanentAccount: 'Account permanente',
		guestAccountWarning: 'I tuoi dati potrebbero essere persi se disinstalli l\'app',
		userId: 'ID utente',
		upgradeAccount: 'Aggiorna account',
		upgradeAccountDesc: 'Crea un account permanente per salvare i tuoi dati',
		upgradeNow: 'Aggiorna ora',
		existingAccount: 'Account esistente',
		existingAccountDesc: 'Accedi per sincronizzare i tuoi dati',
		loginExisting: 'Accedi con un account esistente',
		switchedToExistingAccount: 'Passato all\'account esistente',
		welcomeTagline: 'La tua dispensa intelligente. Zero sprechi.',
		welcomeTitle: 'Benvenuto su Shelfze',
		welcomeSubtitle: 'Traccia il cibo. Genera ricette. Riduci gli sprechi.',
		tryItFirst: 'Provalo prima',
		noAccountNeeded: 'Nessun account necessario per iniziare',
		startScanningNow: 'Inizia a scansionare ora',
		guestScansLimit: 'Limite: 50 scansioni',
		guestRecipesLimit: 'Limite: 5 ricette',
		dataSavedLocally: 'Dati salvati localmente',
		continueAsGuest: 'Continua come ospite',
		createFreeAccount: 'Crea un account gratuito',
		recommended: 'Consigliato',
		freeScansLimit: '250 scansioni/mese',
		freeRecipesLimit: '50 ricette/mese',
		monthlyBonus: 'Bonus mensile',
		syncAcrossDevices: 'Sincronizzazione tra dispositivi',
		secureBackup: 'Backup sicuro',
		getStarted: 'Inizia',
		upgradeAnytime: 'Puoi passare a Premium in qualsiasi momento',
		tier: 'Livello',
		anonymous: 'Anonimo',
		free: 'Gratuito',
		scansRemaining: 'Scansioni rimanenti',
		recipesRemaining: 'Ricette rimanenti',
		unlimited: 'Illimitato',
		upgradeToPremium: 'Passa a Premium',
		limitReached: 'Limite raggiunto',
		scansLimitReached: 'Limite di scansioni raggiunto',
		recipesLimitReached: 'Limite di ricette raggiunto',
		createAccountToGetMore: 'Crea un account per ottenere più scansioni e ricette',
		upgradeToPremiumMessage: 'Passa a Premium per scansioni e ricette illimitate',
		monthlyBonusAdded: 'Bonus mensile aggiunto!',
		giftCode: 'Codice regalo',
		redeemGiftCode: 'Riscatta codice regalo',
		enterGiftCode: 'Inserisci il tuo codice regalo',
		redeem: 'Riscatta',
		giftCodeSuccess: 'Codice regalo riscattato con successo!',
		giftCodeInvalid: 'Codice regalo non valido',
		giftCodeUsed: 'Questo codice è già stato utilizzato',
		giftCodeExpired: 'Questo codice è scaduto',
		haveGiftCode: 'Hai un codice regalo?',
"@

# Find the line with Italian failedToUpdate and insert before the closing })
$pattern = "(\s+failedToUpdate: 'Impossibile aggiornare l'articolo',\r?\n)(\s+\}\),)"
$replacement = "`$1$italianTranslations`r`n`$2"
$content = $content -replace $pattern, $replacement

# Save the file
$content | Set-Content $filePath -NoNewline

Write-Host "✅ Italian translations added successfully!"
