# PowerShell script to insert Slovenian translations

$filePath = "c:\Users\denis\Pantryai\contexts\translations.js"
$content = Get-Content $filePath -Raw

# Slovenian translations to add (88 keys)
$slovenianTranslations = @"
		mediumRecipes: 'Srednje (30-60 min)',
		longRecipes: 'Dolge (> 60 min)',
		allDiets: 'Vse',
		vegetarian: 'Vegetarijansko',
		account: 'Račun',
		myAccount: 'Moj račun',
		login: 'Prijava',
		loginOrSignup: 'Prijava / Registracija',
		createAccount: 'Ustvari račun',
		alreadyHaveAccount: 'Že imate račun?',
		signOut: 'Odjava',
		signOutConfirm: 'Ali ste prepričani, da se želite odjaviti?',
		signedOutSuccess: 'Uspešna odjava',
		loginSuccess: 'Uspešna prijava',
		loginFailed: 'Prijava ni uspela',
		signupFailed: 'Registracija ni uspela',
		upgradeFailed: 'Nadgradnja ni uspela',
		accountCreated: 'Račun uspešno ustvarjen!',
		accountUpgraded: 'Račun uspešno nadgrajen!',
		youNowHave: 'Zdaj imate',
		scans: 'skeniranj',
		password: 'Geslo',
		confirmPassword: 'Potrdi geslo',
		displayName: 'Prikazno ime',
		fillAllFields: 'Prosimo, izpolnite vsa polja',
		passwordsDoNotMatch: 'Gesli se ne ujemata',
		passwordTooShort: 'Geslo mora vsebovati vsaj 6 znakov',
		invalidEmail: 'Neveljaven e-poštni naslov',
		userDisabled: 'Ta račun je bil onemogočen',
		userNotFound: 'Noben račun ni bil najden s tem e-poštnim naslovom',
		wrongPassword: 'Napačno geslo',
		invalidCredentials: 'Neveljavne poverilnice',
		tooManyAttempts: 'Preveč poskusov. Poskusite ponovno pozneje',
		networkError: 'Napaka omrežja. Preverite svojo povezavo',
		emailInUse: 'Ta e-poštni naslov je že v uporabi',
		weakPassword: 'Geslo je prešibko',
		guestAccount: 'Gostovski račun',
		permanentAccount: 'Trajen račun',
		guestAccountWarning: 'Vaši podatki se lahko izgubijo, če odstranite aplikacijo',
		userId: 'ID uporabnika',
		upgradeAccount: 'Nadgradi račun',
		upgradeAccountDesc: 'Ustvarite trajen račun za varno shranjevanje podatkov',
		upgradeNow: 'Nadgradi zdaj',
		existingAccount: 'Obstoječi račun',
		existingAccountDesc: 'Prijavite se za sinhronizacijo podatkov',
		loginExisting: 'Prijavite se z obstoječim računom',
		switchedToExistingAccount: 'Preklopljeno na obstoječi račun',
		welcomeTagline: 'Vaša pametna shramba. Nič odpadkov.',
		welcomeTitle: 'Dobrodošli v Shelfze',
		welcomeSubtitle: 'Sledite hrani. Ustvarjajte recepte. Zmanjšajte odpadke.',
		tryItFirst: 'Najprej preizkusite',
		noAccountNeeded: 'Za začetek ni potreben račun',
		startScanningNow: 'Začnite skenirati zdaj',
		guestScansLimit: 'Omejitev: 50 skeniranj',
		guestRecipesLimit: 'Omejitev: 5 receptov',
		dataSavedLocally: 'Podatki shranjeni lokalno',
		continueAsGuest: 'Nadaljuj kot gost',
		createFreeAccount: 'Ustvari brezplačen račun',
		recommended: 'Priporočeno',
		freeScansLimit: '250 skeniranj/mesec',
		freeRecipesLimit: '50 receptov/mesec',
		monthlyBonus: 'Mesečni bonus',
		syncAcrossDevices: 'Sinhronizacija med napravami',
		secureBackup: 'Varnostna kopija',
		getStarted: 'Začni',
		upgradeAnytime: 'Kadarkoli lahko nadgradite na Premium',
		tier: 'Raven',
		anonymous: 'Anonimen',
		free: 'Brezplačno',
		scansRemaining: 'Preostala skeniranja',
		recipesRemaining: 'Preostali recepti',
		unlimited: 'Neomejeno',
		upgradeToPremium: 'Nadgradi na Premium',
		limitReached: 'Omejitev dosežena',
		scansLimitReached: 'Omejitev skeniranj dosežena',
		recipesLimitReached: 'Omejitev receptov dosežena',
		createAccountToGetMore: 'Ustvarite račun za več skeniranj in receptov',
		upgradeToPremiumMessage: 'Nadgradite na Premium za neomejena skeniranja in recepte',
		monthlyBonusAdded: 'Mesečni bonus dodan!',
		giftCode: 'Darilna koda',
		redeemGiftCode: 'Uveljavi darilno kodo',
		enterGiftCode: 'Vnesite svojo darilno kodo',
		redeem: 'Uveljavi',
		giftCodeSuccess: 'Darilna koda uspešno uveljavljena!',
		giftCodeInvalid: 'Neveljavna darilna koda',
		giftCodeUsed: 'Ta koda je bila že uporabljena',
		giftCodeExpired: 'Ta koda je potekla',
		haveGiftCode: 'Imate darilno kodo?',
"@

# Find the line with Slovenian failedToUpdate and insert before the closing })
$pattern = "(\s+failedToUpdate: 'Izdelka ni bilo mogoče posodobiti',\r?\n)(\s+\}\))"
$replacement = "`$1$slovenianTranslations`r`n`$2"
$content = $content -replace $pattern, $replacement

# Save the file
$content | Set-Content $filePath -NoNewline

Write-Host "✅ Slovenian translations added successfully!"
